### ISSUE TITLE
USER STORY: Deploy to Heroku

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#10]
As a **developer** I want to **deploy the site to Heroku** so that **I can ensure the site works in a production environment and share the completed site publicly**

## Tasks
- [x] Create a new Heroku app
- [x] Add the necessary config vars in Heroku settings
- [x] Ensure a Procfile is added to the Django project
- [x] Add Heroku as an allowed host in Django settings
- [x] Connect the Heroku app to my GitHub repository
- [x] Deploy the site
