### ISSUE TITLE
USER STORY: Register an Account

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#11]
As a **user** I can **register an account** so that **I can log in and out of the site**

## Acceptance Criteria
* **Given** that I do not have an account
**When** I visit the landing page
**Then** I have the option to sign up
* **Given** that I do not not have an account and am on the registration page
**When** I enter my details and password and submit it
**Then** an account is created for me and I am logged in
* **Given** that I have an account
**When** I am logged in
**Then** I cannot see an option to signup and can see an option to logout

## Tasks
- [x] Create functionality for the user to register an account
- [x] Create a registration form
- [x] Create a button or link on the landing page to direct users to the registration page
- [x] Remove the sign-up button or link when the user is logged in and display a logout option
