### ISSUE TITLE
USER STORY: Edit Account Details

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#13]
As a **user** I can **edit my account details** so that **I can keep my account information up to date**

## Acceptance Criteria
* **Given** that I am logged into my account
**When** I view my account page
**Then** I should be able to edit my details
**Given** that I am logged into my account
**When** I click on the edit button on my account page
**Then** I should be directed to a page to edit my details
* **Given** that I am logged into my account
**When** I fill in my new details
**Then** my details are updated for my account

## Tasks
- [x] Create functionality for users to edit their account details
- [x] Add an edit button to the user's account page
- [x] Create a form for users to enter their new details
