### ISSUE TITLE
USER STORY: Delete my Account

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#14]
As a **user** I can **delete my account** so that **I can remove my details and stop using the site at my will**

## Acceptance Criteria
* **Given** that I am logged in to my account
**When** I navigate to my account page
**Then** I have the option to delete my account
* **Given** that I am logged in to my account
**When** I click on the option to delete my account
**Then** I am prompted to confirm the deletion
* **Given** that I am logged in to my account
**When** I confirm the deletion of my account
**Then** my account is deleted
* **Given** that I recently deleted my account
**When** I view the page after deletion
**Then** I receive confirmation of my deletion

## Tasks
- [x] Create a delete button on the user account page
- [x] Create a confirmation prompt to confirm the deletion request
- [x] Create functionality to delete an account
- [x] Create a confirmation message for when the account is deleted
