### ISSUE TITLE
USER STORY: Change my Password

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#15]
As a **user** I can **change my password** so that **I can keep my account secure**

## Acceptance Criteria
* **Given** that I am logged into my account
**When** I navigate to edit my account details page
**Then** I have the option to change my password
* **Given** that I am logged in to my account
**When** I click to change my password
**Then** I am directed to a form to change my password
* **Given** that I am logged in to my account
**When** I successfully fill in the form to change my password and submit it
**Then** I receive feedback that my password has been changed

## Tasks
- [x] Create a form for users to change their password
- [x] Create a button for users to click to change their password
- [x] Create functionality to change a user password
- [x] Provide a feedback message confirming the password change
