### ISSUE TITLE
USER STORY: Reset my Password

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#16]
As a **user** I can **reset my password** so that **I can still access my account if I forget my password**

## Acceptance Criteria
* **Given** that I have forgotten my password
**When**  I try to login 
**Then** An option is available to reset my password
* **Given** that I click on the option to reset my password
**When** I enter the email address I used to signup
**Then** I should receive an email with instructions on how to reset my password
* **Given** that I received the password reset email
**When** I follow instructions to reset my password
**Then** my password is reset

## Tasks
- [x] Create a button for resetting the password
- [x] Create a form for users to input their email address for the password reset
- [x] Ensure the email address entered belongs to a site user
- [x] Create functionality to reset a password
