### ISSUE TITLE
USER STORY: Login and Logout

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#17]
As a **user** I can **login and logout of my account** so that **I can use the site and keep my account secure**

## Acceptance Criteria
* **Given** that I am a registered user that is not logged in
**When** I navigate to the login page and enter my details
**Then** I am logged into my account
* **Given** that I am logged in to my account
**When** I click on the option to logout and confirm the logout request
**Then** I am logged out of my account

## Tasks
- [x] Create functionality for users to login and logout
- [x] Create login and logouts buttons
- [x] Create login and logout forms
