### ISSUE TITLE
USER STORY: Social Media Sign In

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#18]
As a **user** I can **sign in using my social media account** so that **I don't have to remember another password**

## Acceptance Criteria
* **Given** that I want to register for an account
**When** I navigate to the register page
**Then** I am provided with the option to sign in through social media
* **Given** that I click the option to sign in through social media
**When** I enter my details for the selected social media platform
**Then** I am signed in through my social media

## Tasks
- [ ] Create functionality to link the site to social media accounts
- [ ] Create a button for signing in through social media
- [ ] Create functionality for a user to sign in through their social media account
