### ISSUE TITLE
USER STORY: Make a Reservation

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#19]
As a **user** I can **make a reservation request** so that **I can reserve a time and place in the restaurant**

## Acceptance Criteria
* **Given** that I am logged in
**When** I navigate to the reservation page
**Then** I am presented with a form to submit a reservation request
* **Given** that I fill out the form with valid details
**When** I submit the form
**Then** I am provided with feedback that my request has been sent and is awaiting approval
* **Given** that I fill out the form with the same details more than once
**When** I submit the form
**Then** I am provided with feedback that the reservation request has already been made

## Tasks
- [x] Create a button to navigate to the reservation page
- [x] Create a model for reservation records
- [x] Create a reservation form and link it to the model
- [x] Create validation to ensure the same reservation request has not already been made
- [x] Create functionality for a user to submit a reservation request
