### ISSUE TITLE
USER STORY: Receive Reservation Feedback

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#20]
As a **user** I can **receive feedback on whether my reservation has been approved or not** so that **I can visit the restaurant or make new reservation**

## Acceptance Criteria
* **Given** that I submitted a reservation request
**When** I wait for up to 24 hours
**Then** I will receive an email informing me whether or not my reservation has been approved or denied
* **Given** that I submitted a reservation request
**When** I wait for longer than 24 hours
**Then** I can phone the restaurant to follow up my reservation using the number provided on the site

## Tasks
- [x] Create approved, denied, and acknowledged model fields
- [x] Create a template to display pending reservations
- [x] Create buttons to approve or deny reservations
- [x] Create functionality to update the relevant reservation fields when the approve or deny button is clicked
- [x] Add necessary settings and environment variables for email functionality
- [x] Create functionality for an email to be sent to the relevant user when a reservation is approved or denied
