### ISSUE TITLE
USER STORY: Edit Reservations

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#22]
As a **user** I can **edit my reservations** so that **I can change reservation details if I want to**

## Acceptance Criteria
* **Given** that I am logged in and have made a reservation
**When** I view my reservations
**Then** I have the option to edit a reservation provided the date has not passed
* **Given** that I am logged in and have made a reservation
**When** I click the option to edit a reservation
**Then** I am directed to a form with current details and can change them
* **Given** that I am logged in and have made a reservation
**When** I view the page to edit a reservation
**Then** I am provided with a warning that editing the reservation will cancel my current one and the updated version will be subject to approval
* **Given** that I am logged in and have filled in the form to edit a reservation
**When** I submit the form
**Then** I am provided feedback that the new request has been submitted for approval and that I should await confirmation

## Tasks
- [x] Create the template for reservation editing
- [x] Prepopulate the form with current reservation details
- [x] Create a warning message for editing a reservation 
- [x] Create functionality to delete the current reservation and save the new details for approval
