### ISSUE TITLE
USER STORY: Cancel Reservations

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#23]
As a **user** I can **cancel my reservation** so that **I can avoid unnecessary reservations if I change my mind**

## Acceptance Criteria
* **Given** that I am logged in and have made a reservation
**When** I view my reservations
**Then** I have the option to delete a reservation
* **Given** that I am logged in and have made a reservation
**When**  I click the option to delete a reservation
**Then** I am presented with a form to confirm the deletion
* **Given** that I am logged in and have decided to delete my reservation
**When** I confirm the deletion
**Then** The reservation is deleted and I am provided feedback in regards to the deletion

## Tasks
- [x] Create a delete button on the reservation
- [x] Create a confirmation prompt to confirm the deletion request
- [x]  Create functionality to delete the reservation
- [x] Create a confirmation message for when the reservation is deleted
