### ISSUE TITLE
USER STORY: View Staff Dashboard

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#26]
As a **staff member** I can **view the staff dashboard** so that **I can manage the restaurant site and reservations**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I view the navigation bar
**Then** there should be an option to navigate to the dashboard page
* **Given** that I am logged in as a staff member
**When** I navigate to the dashboard page
**Then** I am presented with various information content for the restaurant site
* **Given** that I am logged in as a staff member
**When** I navigate to the dashboard page
**Then** there should be options to manage menu content and reservations

## Tasks
- [x] Create a button to link to the staff dashboard
- [x] Create a template to contain the dashboard page content
- [x] Create functionality to display informational content about the restaurant site
- [x] Create button options for managing the menu and reservations
