### ISSUE TITLE
USER STORY: Restrict Certain Features To Registered Users

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#27]
As a **site owner** I want to **restrict certain features to registered users** so that **it encourages people to register to the site and ensures reservations are recorded for known customers**

## Acceptance Criteria
* **Given** that a user is not logged in
**When** they view the site
**Then** there is no option to view an account page
* **Given** that a user is not logged in
**When** they click the option to make a reservation
**Then** they are unable to make a reservation unless logged in
* **Given** that a user is not logged in
**When** they view the menu page
**Then** they are unable to rate a menu item
* **Given** that a user is not logged in
**When** they attempt to perform an action that requires a logged-in user
**Then** they are prompted to log in before they are able to do so

## Tasks
- [ ] Create functionality to restrict relevant features to authenticated users
- [ ] Add different template content depending on whether a user is authenticated
- [ ] Create messages for feedback when a user tries to access a restricted page
- [ ] Create prompt messages to ask users to log in to perform desired actions
