### ISSUE TITLE
USER STORY: Restrict Certain Features To Staff

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#28]
As a **site owner** I want to**restrict certain features to staff members** so that **I can ensure unauthorized users cannot tamper with the running of the site**

## Acceptance Criteria
* **Given** that a user is **not** a staff member
**When** they visit the site
**Then** there is no option to view the dashboard page
* **Given** that a user is **not** a staff member
**When** they view the menu
**Then** they are unable to make changes to the menu items and options to do so are unavailable
* **Given** that a user is **not** a staff member
**When** they try to access the dashboard page
**Then** they are provided with feedback that they are not authorized to view the page
* **Given** that a user **is** a staff member
**When** they visit the site
**Then** they are able to view and manage the dashboard page and related features
* **Given** that a user **is** a staff member
**When** they view the menu
**Then** they are able to make changes to the menu and are provided with available options to do so

## Tasks
- [x] Allocate staff roles to desired users in the Django admin panel
- [x] Create functionality to restrict relevant features to staff users
- [x] Add different template content to display for staff users
- [x] Create messages for feedback when a user tries to access a restricted page
