### ISSUE TITLE
USER STORY: Staff Can View Reservations In Categories

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#29]
As a **staff member** I can **view all reservations in categories** so that **I can manage all reservations that come through the site**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I am on the dashboard page
**Then** There is a section of the page related to reservations
* **Given** that I am logged in as a staff member
**When** I view the reservations section of the dashboard
**Then** There are options to view reservations in different categories (pending, approved, and denied)
* **Given** that I am logged in as a staff member
**When** I click on an option to view reservations for a certain category
**Then** I am directed to a page with a list of relevant reservations
* **Given** that I am logged in as a staff member
**When** I visit a page for reservations and there are no reservations for that category
**Then** I am provided with feedback that there are no reservations for the category

## Tasks
- [x] Create a reservations section in the dashboard page
- [x] Create buttons for each category to link to pages containing relevant reservations
- [x] Create pages to display reservation lists in each category
- [x] Create a feedback message to inform the user if no reservations are present
