### ISSUE TITLE
USER STORY: Staff Can Create Reservations

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#30]
As a **staff member** I can **create a reservation at a customer's request** so that **I can save a reservation on behalf of a customer at the restaurant**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I navigate to the page to make a reservation
**Then** I can fill in a form to make the reservation
* **Given** that I am logged in as a staff member
**When** I am filling in the form to make a reservation
**Then** There is an option to mark the reservation as approved in the form
* **Given** that I am logged in as a staff member
**When** I am filling in the form to make a reservation
**Then** There is an option to add the customer's account to save the reservation for

## Tasks
- [ ] Create functionality to display the approval option in the reservation form if the user is staff
- [ ] Create functionality to save the reservation as approved without needing extra approval in the dashboard
- [ ] Create functionality to save the reservation to the customer's profile if they have an account
