### ISSUE TITLE
USER STORY: Staff Can Edit Reservations

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#31]
As a **staff member** I can **edit a reservation at the request of a customer** so that **I can ensure all bookings are up to date if a customer changes their mind about their reservation**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I navigate to the approved reservations page from the dashboard
**Then** there is an option on the reservation to edit it
* **Given** that I am logged in as a staff member
**When** I click the button to edit a reservation
**Then** I am directed to a prepopulated form relating to the reservation
* **Given** that I am logged in as a staff member
**When** I fill in the form with the new details and submit it
**Then** the new reservation is saved and feedback is provided informing me
* **Given** that I am logged in as a staff member
**When** I edit a reservation
**Then** an email is sent to inform the customer of the change confirmation

## Tasks
- [ ] Add an edit button to reservations if the user is staff
- [ ] Prepopulate the form with current reservation details
- [ ] Create functionality to delete the current reservation and save the new details as approved
