### ISSUE TITLE
USER STORY: Staff Can Cancel Reservations

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#32]
As a **staff member** I can **cancel reservations on behalf of a customer** so that **I can ensure unnecessary reservations are not kept**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I navigate to the approved reservations page from the dashboard
**Then** there is an option to cancel the reservation
* **Given** that I am logged in as a staff member
**When** I click on the button to cancel the reservation
**Then** I am prompted to confirm the deletion request
* **Given** that I am logged in as a staff member and choose to delete a reservation
**When** I confirm the deletion request
**Then** the reservation is deleted and a confirmation message is shown
* **Given** that I am logged in as a staff member
**When** I delete a reservation item
**Then** feedback is sent to the relevant customer about the cancelation

## Tasks
- [ ] Create a delete button on reservations
- [ ] Create a confirmation prompt to confirm the deletion
- [ ] Create functionality to delete the reservation
- [ ] Create a feedback message to inform the customer of the cancelation
