### ISSUE TITLE
USER STORY: View Reservations for current date

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#33]
As a **staff member** I can **view all reservations for the current date** so that **I know what to plan for on the day at the restaurant**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I view the reservations section in the dashboard page
**Then** there should be an option to view today's reservations
* **Given** that I am logged in as a staff member
**When** I click on the option to view today's reservations
**Then** I should be directed to a page which displays all approved reservations for the current date
* **Given** that I am logged in as a staff member and there are no reservations on the current date
**When** I navigate to the page to view today's reservations
**Then** a feedback message is provided informing me that there are no reservations for today

## Tasks
- [x] Create a button in the reservations section of the dashboard page to link to today's reservations
- [x] Create functionality to get all approved reservations for the current date
- [x] create a template to display the reservations
