### ISSUE TITLE
USER STORY: Search Reservations By Name

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#35]
As a **staff member** I can **search reservations pertaining to a name** so that **I can find out the reservation status of the restaurant for a given name**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I navigate to the reservations section of the dashboard page
**Then** There is an option to search reservations by name
* **Given** that I am logged in as a staff member and I want to search for a name
**When** I enter a valid name to search for
**Then** all reservations pertaining to that name are displayed
* **Given** that I am logged in as a staff member and I want to search for a date but no reservations exist for the date
**When** I enter a valid name to search for
**Then** feedback is provided to inform me that no reservations exist for the specified name

## Tasks
- [x] Create a search field with functionality to search by name in the staff dashboard
- [x] Create functionality to get all reservations for the specified name
- [x] Create a page to view the search results
- [x] Create functionality to check if no reservations exist for the name
- [x] Create a feedback message to inform the user if no reservations exist for the searched name
