### ISSUE TITLE
USER STORY: Add Menu Items

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#36]
As a **staff member** I can **add a menu item** so that **I can keep the menu up to date with new options**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I navigate to the staff dashboard
**Then** there is a section for managing the menu with a button to add a new item
* **Given** that I am logged in as a staff member and I want to add a menu item
**When** I click the button to add a new item
**Then** I am directed to a menu item form
* **Given** that I am logged in as a staff member and click on the option to add a new item
**When** I fill in the fields and submit the form
**Then** the new menu item is saved and feedback is provided to inform me that it was saved successfully
* **Given** that I am logged in as a staff member and want to save the item as a draft
**When** I fill in the form and adjust the status field to "draft"
**Then** the menu item is saved as a draft
* **Given** that I am logged in as a staff member and add a new menu item
**When** I save the item as published
**Then** the menu item is displayed on the site menu to all users
* **Given** that I am logged in as a staff member and add a new menu item
**When** I save the item as a draft
**Then** the menu item is saved but not displayed to all users and is displayed in the drafts page

## Tasks
- [x] Create a section in the staff dashboard for menu management
- [x] Create a button linking to the form to add a new menu item
- [x] Create a model with fields for menu items
- [x] Add necessary settings and variables to upload a picture to Cloudinary through the form
- [x] Create a form for creating a new menu item
- [x] Create functionality to save a menu item
- [x] Create functionality to check whether the item is published or a draft and display it in the right page
- [x] Add a feedback message to inform the user of successfully adding a menu item
