### ISSUE TITLE
USER STORY: Edit Menu Items

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#37]
As a **staff member** I can **edit menu items** so that **ensure the correct menu information is displayed**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I view menu items on the menu page or drafts page
**Then** there is an edit button to edit the item
* **Given** that I am logged in as a staff member
**When** I click the edit button on a menu item
**Then** I am directed to a prepopulated form with current data
* **Given** that I am logged in as a staff member
**When** I view the form to edit the menu item
**Then** I can change any part of the form to update it
* **Given** that I am logged in as a staff member and edit a menu item
**When** I edit the status field from published to draft or vice versa
**Then** the field is updated and the location where the menu item is displayed is changed (menu page for published items and drafts page for drafts)
* **Given** that I am logged in as a staff member and edit a menu item
**When** I submit the form
**Then** I am provided feedback that the item was updated

## Tasks
- [ ] Add an edit button to menu items to link to the edit form
- [ ] Create functionality to prepopulate the form with the current data
- [ ] Create functionality to update the menu item with new data when the edit form is submitted
- [ ] Add a feedback message to inform the user when a menu item is updated
