### ISSUE TITLE
USER STORY: Delete Menu Items

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#38]
As a **staff member** I can **delete menu items** so that **I can remove old menu items that are no longer relevant**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I view menu items on the menu page or drafts page
**Then** there is a button to delete the menu item
* **Given** that I am logged in as a staff member
**When** I click on the button to delete a menu item
**Then** I am presented with a confirmation prompt to confirm my deletion request
* **Given** that I am logged in as a staff member
**When** I confirm the deletion
**Then** the menu item is deleted and feedback is provided to inform me of the successful deletion

## Tasks
- [x] Add a delete button to menu items for staff users
- [x] Create a deletion confirmation prompt to confirm the user's deletion request
- [x] Create functionality to delete the menu item
- [x] Create a feedback message to inform the user of successful deletion
