### ISSUE TITLE
USER STORY: Mark Menu Items As Unavailable

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#39]
As a **staff member** I can **mark a menu item as unavailable** so that **I can still display the item but inform customers that it is currently unavailable**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I add or edit a menu item
**Then** there is an option to mark the item as unavailable
* **Given** that I am logged in as a staff member and am editing a menu item
**When** I change the availability status to unavailable 
**Then** the menu item gets labeled as unavailable
* **Given** that I am logged in as a staff member
**When** I change the availability status back to available 
**Then** the menu item unavailable label is not displayed

## Tasks
- [x] Add an availability boolean field to the menu item model with a default of True
- [x] Add the field to the menu item form for users to change it when they edit or add menu items
- [x] Create functionality to display a label when an item is marked as unavailable
