### ISSUE TITLE
USER STORY: View Menu Item Images

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#40]
As a **user** I can **view images of menu items** so that **I can visualize the food item**

## Acceptance Criteria
* **Given** that I am viewing the menu page
**When** I click on a menu item
**Then** a modal appears with an image of the menu item
* **Given** that a menu item has no picture added
**When** I click on a menu item
**Then** a modal appears with a default message informing the user that no image is available

## Tasks
- [x] Ensure a cloudinary field is added to the menu item model
- [x] Add modal functionality to the menu page to open modals when menu items are clicked
- [x] Display the menu item image in the modal when the menu item is clicked
- [x] Ensure a default is in place with a message to inform the users that no image is available when no image is added to the menu item
