### ISSUE TITLE
USER STORY: Rate Menu Items

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#41]
As a **user** I can **rate menu items** so that **I can share my opinion about the food**

## Acceptance Criteria
* **Given** that I am logged in and viewing the menu page
**When** I click a menu item
**Then** a modal should appear with the option to rate the menu item
* **Given** that I am logged in and have opened a menu item modal
**When** I click the option to rate the item
**Then** I am presented with a selection out of 5 stars to choose from to rate the menu item
* **Given** that I am logged in and rate a menu item
**When** I have rated the item and view the modal again
**Then** my rating should be added to the menu item

## Tasks
- [ ] Create a field for rating out of 5 with the menu model for the logged in user
- [ ] Add a button to the menu item modal for rating it
- [ ] Add a selection form for a user to submit their rating
- [ ] Add a section to display the user's rating on the menu item
