### ISSUE TITLE
USER STORY: Delete Menu item Ratings

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#44]
As a **user** I can **delete my rating on a menu item** so that **I can choose not to rate it if I don't want to**

## Acceptance Criteria
* **Given** that I am logged in viewing the menu and have rated a menu item
**When** I click on the menu item to open the modal
**Then** there is an option to delete my rating
* **Given** that I am logged in and have opened the menu item modal
**When** I click on the option to delete my rating
**Then** I am presented with a prompt to confirm my deletion request
* **Given** that I am logged in and want to delete my rating
**When** I confirm the deletion
**Then** my rating is deleted and is no longer displayed

## Tasks
- [ ] Add a delete button to the menu item rating if the user has an existing rating
- [ ] Create a confirmation prompt for the user to confirm the deletion of their rating
- [ ] Create functionality to delete the rating for the logged-in user on the menu item
- [ ] Ensure the rating is completely deleted and is no longer included in the average rating calculation
