### ISSUE TITLE
USER STORY: Staff Reservation Approval/Denial

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#45]
As a **staff member** I can **approve or deny reservations** so that **I can be in control of reservations at the restaurant**

## Acceptance Criteria
* **Given** that I am logged in as a staff member
**When** I navigate to the pending reservations page
**Then** there are options on each reservation to approve or deny it
* **Given** that I am viewing pending reservations as a staff member
**When** I click the option to approve the reservation
**Then** the reservation is approved
* **Given** that I am viewing pending reservations as a staff member
**When** I click the option to deny the reservation
**Then** the reservation is denied

## Tasks
- [x] Create functionality to approve and deny reservations.
- [x] Add buttons to approve or deny reservations in the pending reservation page.
- [x] Ensure functionality is only accessible by staff users.
