### ISSUE TITLE
USER STORY: Setup Django

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#8]
As a **developer** I want to **set up Django and install the initial supporting libraries needed** so that **I can begin development of the site**

## Tasks
- [x] Install Django
- [x] Install and connect the database
- [x] Install and connect Cloudinary
- [x] Create and populate a requirements.txt file
- [x] Create a Django project
- [x] Create the first app needed and connect it in settings.py
