### ISSUE TITLE
USER STORY: Secure Config Variables

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/bundu-restaurant#9]
As a **developer** I want to **set up the environment to secure secret configuration variables** so that **I can ensure sensitive data is kept private**

## Tasks
- [x] Create an env.py file to store the secret environment variables
- [x] Adjust settings and code to direct to the added location for any secret variables
- [x] Ensure the env.py file is added to .gitignore to avoid pushing sensitive data to GitHub
